# Generated by Django 4.2.3 on 2023-08-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount_recieved', models.IntegerField(default=0)),
                ('issued_to', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareApp.product')),
            ],
        ),
    ]
