# Generated by Django 4.2.3 on 2023-08-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareApp', '0004_rename_sales_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recieved_quantity',
            new_name='received_quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='amount_recieved',
            new_name='amount_received',
        ),
    ]
